//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace React_Store.Models
{
    using System;
    using System.Collections.Generic;
    using React_Store.Interfaces;

    public partial class Locker:ILocker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Locker()
        {
            this.LockerLists = new HashSet<LockerList>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> LockerBanksID { get; set; }
    
        public virtual LockerBank LockerBank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LockerList> LockerLists { get; set; }
    }
}
