//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace React_Store.Models
{
    using System;
    using System.Collections.Generic;
    using React_Store.Interfaces;
    
    public partial class LockerList:ILockerList
    {
        public int ID { get; set; }
        public int LocationID { get; set; }
        public int LockerBanksID { get; set; }
        public int LockersID { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual LockerBank LockerBank { get; set; }
        public virtual Locker Locker { get; set; }
    }
}
